### ISSUE TITLE
V2.0.0

### ISSUE THREAD

**Issue by lacherogwu** [dcasella/monokai-plusplus#21]
Hello, I've noticed the color scheme changed a lot after the update to 2.0.0
The previous version colored looked much better, and now it's coloring many things in orange. see here
I added the version inside the pictures.

Sidebar colors changed, props in js files changed, many things, you can see the picture below.
<img width="3370" alt="image" src="https://user-images.githubusercontent.com/49835614/176119197-e1cdbf1b-5ee1-44d9-a280-b05a437f0a14.png">

**Comment by takapiro99** [comment]
@lacherogwu 

I think that's exactly right.
It's a disappointment that the visibility is so poor...

It was my very favorite and best theme. Hope it will be improved.

**Comment by lacherogwu** [comment]
> @lacherogwu
> 
> I think that's exactly right. It's a disappointment that the visibility is so poor...
> 
> It was my very favorite and best theme. Hope it will be improved.

Yeah it is the best out there, as a quick solution you can install v1.10.0 so the colors scheme will back to normal, that's what I did for now.

**Comment by dcasella** [comment]
Hi, I pushed a new version (2.0.1) which reverts all workbench colors to the default.
It also introduces a new theme, Monokai++ Unified, which includes the workbench colors (sidebar, footer, etc.) as I want them.

Colors can always be overriden via [Settings](https://code.visualstudio.com/docs/getstarted/themes#_workbench-colors) ([full documentation](https://code.visualstudio.com/api/references/theme-color)).

In the next days I'll try to see what I can do about the orange parameters.

**Comment by dcasella** [comment]
Let's talk about the orange stuff. I absolutely agree that too much orange doesn't make sense.

The object parameters will keep being orange because properties are handled differently than variables, and it should be reflected in the syntax highlighting in my opinion.
So this is what I came up with:
![image](https://user-images.githubusercontent.com/19588895/176257999-d846b3f8-22d6-4bc8-a79b-508b0d325a72.png)
I would like to find a way to match function parameters with their references (for example `isDownloading` should be different from `download`), but I can't decide how.

I'm releasing 2.0.2 soon to partially revert the VS Code Semantic Highlighting troubles. Please make sure to update to the latest version so you can keep providing useful feedback!

Thanks a lot.

**Comment by lacherogwu** [comment]
Thanks a lot, it makes much more sense now I totally agree with you

I like the idea of highlighting function parameters different.

Appreciate your valuable time 🙏

**Comment by dcasella** [comment]
I'm closing the issue since 2.0.2 is now released.
I'll post here when I get an idea on how to match function parameters with their references.

**Comment by dcasella** [comment]
What about italic? (notice the `device` parameter)
![image](https://user-images.githubusercontent.com/19588895/176275540-1b089cee-3a61-421a-a892-07c7ce0fd632.png)

**Comment by lacherogwu** [comment]
I think it's a little bit in conflict with your intention, it's hard to notice any difference, I would go for a color, maybe a bit lighter one

**Comment by takapiro99** [comment]
@dcasella 
Big Thanks for your quick response!!
